### ISSUE TITLE
Load my text

### ISSUE THREAD

**Issue by kladovschik** [dmesquita/understanding_tensorflow_nn#3]
How can I load my text for classification?

P.S. Sorry for my knowledge of English language.

**Comment by dmesquita** [comment]
Hi there! Do you mean "train the model with your own data" or "make a prediction with the model we already built"?

Thanks!

**Comment by kladovschik** [comment]
I mean "train the model with my own data"

**Comment by dmesquita** [comment]
Nice, then you just need to change the `get_batch()` method to deal with your own data. In what format is your data stored?

**Comment by kladovschik** [comment]
txt and CSV. These are different sets of data.

**Comment by dmesquita** [comment]
Have you tried to load them to feed the `get_batch()` method? What's the issue?

**Comment by kladovschik** [comment]
thanks for the help
